name: qgrid-test
channels:
  - conda-forge
  - defaults
dependencies:
  - pip:
    - jupyterlab
    - qgrid
    - gensim
    - spacy
    - pandas
    - flashtext
    - matplotlib
    - seaborn
    - pyLDAvis
    - numpy