name: qgrid-test
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - qgrid==1.1.1
  - gensim==3.7.0
  - spacy==2.0.18
  - pandas==0.23.4
  - flashtext==2.7
  - matplotlib==3.0.2
  - seaborn==0.9.0
  - pyLDAvis==2.1.2
  - numpy==1.15.4